# Use gcc Docker Image
image: gcc

# Build Stage: Compile and Link Libraries and Executables
build:
  stage: build
  timeout: 8 hours

  # Download and Install make, cmake, python3, pip3, googletest, spdlog, and gcovr
  before_script:
    - apt -y update && apt -y install make cmake git python3 python3-pip build-essential
    - mkdir -p /opt && cd /opt
    - git clone https://github.com/google/googletest.git
    - cd googletest
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .
    - make -j
    - make install
    - cd /opt
    - git clone https://github.com/gabime/spdlog.git
    - cd spdlog
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    - make install
    - cd /opt
    - git clone https://github.com/linux-test-project/lcov.git
    - make -C lcov install
    - pip3 install gcovr
    - cd $CI_PROJECT_DIR

  # Build Debug, Release, and Code Coverage versions of Source
  script:
    - mkdir -p cmake-build-release
    - cd cmake-build-release
    - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ..
    - make -j
    - cd ../
    - mkdir -p cmake-build-coverage
    - cd cmake-build-coverage
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -G "CodeBlocks - Unix Makefiles" ..
    - make -j
    - make BitmaskCoverage
    - make BoardCoverage
    - make ChessClockCoverage
    - make ChessMoveCoverage
    - make StringManipCoverage
    - make UCIOptionsCoverage
    - make EvalCoverage
    - make PerftCoverage
    - lcov --add-tracefile BitmaskCoverage.info --add-tracefile BoardCoverage.info --add-tracefile ChessClockCoverage.info --add-tracefile ChessMoveCoverage.info --add-tracefile StringManipCoverage.info --add-tracefile UCIOptionsCoverage.info --add-tracefile EvalCoverage.info --add-tracefile PerftCoverage.info --output-file CompleteCoverage.info
    - lcov --remove CompleteCoverage.info '/usr/local/*' '/usr/include/*' -o CompleteCoverageFiltered.info

  # Extract everything in each cmake build directory
  artifacts:
    paths:
      - cmake-build-release/
      - cmake-build-coverage/

# Run all test executables
test:
  timeout: 8 hours

  stage: test
  script:
    - ./cmake-build-release/test/BitmaskTestRunner
    - ./cmake-build-release/test/BoardTestRunner
    - ./cmake-build-release/test/ChessClockTestRunner
    - ./cmake-build-release/test/ChessHashTestRunner
    - ./cmake-build-release/test/ChessMoveTestRunner
    - ./cmake-build-release/test/EvalTestRunner data/eval-test/FullEvalTest.fen
    - ./cmake-build-release/test/StringManipTestRunner
    - ./cmake-build-release/test/UCIOptionsTestRunner
    - ./cmake-build-release/test/PerftTestRunner data/perft/positions.perft
