image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make cmake git
    - mkdir -p /opt && cd /opt
    - git clone https://github.com/google/googletest.git
    - cd googletest
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .
    - make -j
    - make install
    - cd /opt
    - git clone https://github.com/gabime/spdlog.git
    - cd spdlog
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    - make install
    - cd $CI_PROJECT_DIR
  script:
    - mkdir -p cmake-build-debug
    - cd cmake-build-debug
    - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" ..
    - make -j
    - cd ../
    - mkdir -p cmake-build-release
    - cd cmake-build-release
    - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ..
    - make -j
    - cd ../
    - mkdir -p cmake-build-coverage
    - cd cmake-build-coverage
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -G "CodeBlocks - Unix Makefiles" ..
    - make -j
  artifacts:
    paths:
      - cmake-build-debug/
      - cmake-build-release/
      - cmake-build-coverage/

test:
  stage: test
  script:
    - ./cmake-build-debug/test/AttackTestRunner
    - ./cmake-build-debug/test/BitmaskTestRunner
    - ./cmake-build-debug/test/BoardTestRunner
    - ./cmake-build-debug/test/ChessClockTestRunner
    - ./cmake-build-debug/test/ChessHashTestRunner
    - ./cmake-build-debug/test/ChessMoveTestRunner
    - ./cmake-build-debug/test/EvalTestRunner
    - ./cmake-build-debug/test/StringManipTestRunner
    - ./cmake-build-debug/test/UCIOptionsTestRunner
    - ./cmake-build-debug/test/AttackTestRunner
    - ./cmake-build-release/test/BitmaskTestRunner
    - ./cmake-build-release/test/BoardTestRunner
    - ./cmake-build-release/test/ChessClockTestRunner
    - ./cmake-build-release/test/ChessHashTestRunner
    - ./cmake-build-release/test/ChessMoveTestRunner
    - ./cmake-build-release/test/EvalTestRunner
    - ./cmake-build-release/test/StringManipTestRunner
    - ./cmake-build-release/test/UCIOptionsTestRunner
